errors rework
themotte/rDrama pull request #434
Opened 2022-11-21 19:38 UTC by justcool393

one of the first things i did is do an errors rework over on rdrama. this provides a simple and relatively stable way to abort out of a function quickly, using Flask's abort. we can provide extra details to the user

for example

![image](https://user-images.githubusercontent.com/1238820/203143664-c7b93650-f240-440e-a1e2-45c36c398802.png)

this message also is displayed in the API as well

see also:
https://github.com/Aevann1/rDrama/pull/400
https://github.com/justcool393/rDrama/tree/errors-rework

this also adds the 409 code (i'm amenable to changing the message)

2022-11-22 08:53 UTC, justcool393 commented
looks to be good. have tested it and it should work pretty well

2022-11-29 16:00 UTC, TLSM requested changes

2022-11-29 16:00 UTC, TLSM commented on files/routes/posts.py
> +from files.helpers.discord import send_discord_message, send_cringetopia_message
You accidentally a line.

2022-11-29 16:00 UTC, TLSM commented on files/routes/posts.py
> +		send_discord_message(post.permalink)
A line.

2022-11-29 16:00 UTC, TLSM commented on files/routes/posts.py
> +		send_discord_message(post.permalink)
... a line.

2022-11-29 16:00 UTC, TLSM commented on files/routes/posts.py
> +	if not url or '\\' in url: abort(400)
Merge up?

2022-11-29 16:25 UTC, justcool393 commented on files/routes/posts.py
> +	if not url or '\\' in url: abort(400)
again not sure how this got in here but... sure why not

2022-11-29 16:29 UTC, justcool393 commented
ty
if you could also just spot check my merge too i'd rly appreciate it

2022-11-29 17:07 UTC, TLSM approved these changes
Tested locally:
  - Server starts, viewing common pages, submitting new posts, and commenting all still work.
  - cURL request while bots disabled gets a properly formed 403 JSON response body.
  - Error toast correctly displays in UI on comment 403.
  - Submitting a post with empty title (after bypassing frontend verification) correctly gets a 400 page "Minimum length for title is 1".

Also we have very similar errors.py logic on the upstream already which has been stable for a number of weeks. If there's any bug here, it'd likely be localized to a particular `abort(...)` location.

2022-12-02 02:58 UTC, merged

2022-12-02 02:58 UTC, zorbathut commented
Lookin' good!

If at any point you can deduplicate some of that

```
if (data && data["error"]) document.getElementById('toast-post-error-text').innerText = data["error"];
if (data && data["details"]) document.getElementById('toast-post-error-text').innerText = data["details"];
```

stuff, that would also be great :V

2023-04-08 21:22 UTC, justcool393 commented
agreed. will put it on a todo. it's mostly a weird artifiact of this fork having like 5 posttoast variations