solve blocking weaponization
themotte/rDrama pull request #436
Opened 2022-11-28 15:24 UTC by justcool393

fixes #175

2022-11-28 15:33 UTC, justcool393 commented
this should be it but it needs testing

2022-11-28 16:06 UTC, TLSM requested changes
The change to User.userblocks looks to correctly make blocks more unidirectional: blocks no longer prevent the blockee from seeing the blocker's content or replying to them, while still allowing the blocker to not be notified of nor otherwise see the blockee.

Change requested to fix a bug resulting from changing comment_on_publish signature, also clarifying some UI text.

2022-11-28 16:06 UTC, TLSM commented on files/routes/comments.py
> +def comment_on_publish(comment:Comment, replying_to_blocked:bool):
`comment_on_publish` is used in at least one other location (admin.py for approving filtered comments) so if the signature is going to change, you have to propagate it there too. However, I think it might be better to move replying_to_blocked into the User model somehow and just call it separately inside comment_on_publish and the api_comment route.

2022-11-28 16:06 UTC, TLSM commented on files/templates/settings_blocks.html
> +				<p class="text-small text-muted mb-md-0">You have blocked the following users. They cannot notify you with a username mention.</p>
It also means a blocker doesn't see other sources of notifications from their blockee (namely reply notifs) and also their blockee's comments are hidden.

2022-11-28 18:12 UTC, TLSM approved these changes
Tested and requested changes work correctly on happy paths for new reply comment and filtered comment approval. Probably still some untested edge cases, but it at least won't violently break prod if so.

2022-12-02 03:01 UTC, zorbathut commented
Looks good!

(1) Something I checked in before is conflicting, sorry (I suspect it's the big error change.)

(2) I'm gonna make a meta post asking about this before I actually merge this in, though I doubt there will be major problems.

2022-12-17 17:11 UTC, merged