[#451][WIP] Add count of collapsed comments in the collapsed comment thingy
themotte/rDrama pull request #459
Opened 2022-12-31 10:38 UTC by faul-sname

2023-01-07 02:30 UTC, faul-sname commented on files/helpers/comments.py
> +		except: pass
This was moved from `files/routes/comments.py`, but this might still represent a legit problem -- I'm not sure what a "pusher thread" is here.

2023-01-08 04:25 UTC, zorbathut requested changes
One minor change that I think is not actually fixing a thing that is a problem, but is worth patching up anyway.

Rest of it looks good!

2023-01-08 04:25 UTC, zorbathut commented on files/helpers/comments.py
> +		except: pass
I'm not sure if this is something we're actually using - I suspect not - but at the least, the `pusher_thread` function should be moved into this file as well, which is an easy "fix" just in case.

2023-01-09 08:09 UTC, faul-sname commented on files/helpers/comments.py
> +		except: pass
Ah, that makes sense, and yeah turns out I'm not sure what it is because I failed to import it.

Anyway, fixed. Good catch, thanks.

2023-01-09 08:16 UTC, zorbathut approved these changes

2023-01-13 09:53 UTC, zorbathut approved these changes

2023-01-13 10:09 UTC, zorbathut requested changes

2023-01-13 10:09 UTC, zorbathut commented on migrations/versions/2023_01_03_07_59_56_1f30a37b08a0_dml_populate_comments_descendant_count_.py
> +
I suspect there's an issue in here. The Github tests are timing out after 24 hours, and when I tried running it locally, it ran for a few minutes on this step before I killed it. Given how few comments I have locally, something is very broken here.

Recommend checking out the Frost branch, populating test data (possibly with the test-data-gen script), and then seeing if this works. If it works for you then I'm confused :V but let me know what you get!

2023-01-14 09:15 UTC, zorbathut approved these changes

2023-01-14 09:15 UTC, merged