volunteer: hide usernames and scores in volunteer (ref #454)
themotte/rDrama pull request #465
Opened 2023-01-08 09:09 UTC by justcool393

completely untested lol but it should work

2023-01-09 03:06 UTC, zorbathut commented
This does not seem to work, I'm afraid.

![image](https://user-images.githubusercontent.com/160754/211235013-90e1ffe2-e55d-4ae7-a576-17f7d6f0037c.png)

Please test next time!

2023-01-09 03:07 UTC, zorbathut requested changes
(sigh, it wants me to write a thing here. fix plz)

2023-02-04 09:07 UTC, TLSM commented on files/templates/volunteer_janitor.html
> +                    {% set should_hide_username = false %}
Perhaps it doesn't work because this is `false`?

Just need to make sure that this doesn't break behavior elsewhere when undefined.

2023-02-04 09:23 UTC, TLSM approved these changes
Tested locally, works:
![image](https://user-images.githubusercontent.com/104547575/216759462-719ba8a1-87d5-4c42-b73f-c98312f8277b.png)

No visible regressions in other places `comments.html` is used (post display, notifications), and quickly truth tabling the boolean expressions suggests they should behave correctly for `should_hide_{score,username} ∈ {None, True, False}`

2023-02-07 13:04 UTC, zorbathut approved these changes

2023-02-07 13:04 UTC, merged