Adding usernotes
themotte/rDrama pull request #70
Opened 2022-05-14 17:03 UTC by mjhouse

This adds a dialog accessible only to mods by clicking '_U_' next to a users name on the comments/posts and post listing pages. The dialog allows mods to create usernotes tagged with the labels listed in #14.
![Screenshot from 2022-05-14 11-59-19](https://user-images.githubusercontent.com/4141157/168441587-9d324be2-a0ae-438c-b18d-0bbf7e0658fc.png)

2022-05-15 12:09 UTC, zorbathut requested changes

2022-05-15 12:09 UTC, zorbathut commented on files/helpers/wrappers.py
> -					if not v.validate_formkey(submitted_key): abort(401)
It looks like the changes in this file aren't actually changes, just a little reformatting. They seem like reasonable reformatting to do but can we split this into a separate change request?

2022-05-15 12:09 UTC, zorbathut commented on files/templates/comments.html
> -{% if not ajax %}
Github is flagging this entire file as changed :V I think it must've been an indent or CRLF change; can this be simplified? Alternatively, if it really is a necessary formatting change, gimme a pull request for the formatting change *first* to make the real content change less intrusive and easier to track later.

2022-05-15 12:09 UTC, zorbathut commented
Overall: Looks really good! I've got two comments and both of them are just cleaning up the changelist a little.

If we've got the Alembic stuff in by the time this is ready then I'll also be asking you to do the Alembic update process, otherwise we'll change the Alembic changelist to take this into account instead :)

2022-05-16 10:13 UTC, mjhouse commented on files/helpers/wrappers.py
> -					if not v.validate_formkey(submitted_key): abort(401)
That was left over from debug code I added and removed while I was figuring out how to send POST requests to the api. I've reverted it.

2022-05-16 10:31 UTC, mjhouse commented on files/templates/comments.html
> -{% if not ajax %}
I'm not sure why it was saying the whole file was changed, but I rolled it back, reintroduced my changes and up-merged from master and it isn't flagging it anymore.

2022-05-16 10:47 UTC, mjhouse commented
@zorbathut I think I've resolved your issues, but you have to do the actual merge. Let me know if you want me to do anything else.

2022-05-16 16:52 UTC, zorbathut approved these changes

2022-05-16 16:53 UTC, merged